name: build

on: [push, pull_request]

env:
  DEFAULT_COMPOSER_FLAGS: "--prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpunit:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 7.3
            extensions: apc, curl, dom, mbstring, pdo, pdo_sqlite, sqlite3, json, xml, xmlwriter, tokenizer, openssl, iconv
          - php: 7.4
            extensions: apc, curl, dom, mbstring, pdo, pdo_sqlite, sqlite3, json, xml, xmlwriter, tokenizer, openssl, iconv
          - php: 8.0
            extensions: apcu, curl, dom, mbstring, pdo, pdo_sqlite, sqlite3, json, xml, xmlwriter, tokenizer, openssl, iconv
          - php: 8.1
            extensions: apcu, curl, dom, mbstring, pdo, pdo_sqlite, sqlite3, json, xml, xmlwriter, tokenizer, openssl, iconv
          - php: 8.2
            extensions: apcu, curl, dom, mbstring, pdo, pdo_sqlite, sqlite3, json, xml, xmlwriter, tokenizer, openssl, iconv
          - php: 8.3
            extensions: apcu, curl, dom, mbstring, pdo, pdo_sqlite, sqlite3, json, xml, xmlwriter, tokenizer, openssl, iconv
          - php: 8.4
            extensions: apcu, curl, dom, mbstring, pdo, pdo_sqlite, sqlite3, json, xml, xmlwriter, tokenizer, openssl, iconv

    steps:
      - name: Checkout.
        uses: actions/checkout@v4

      - name: Install PHP.
        uses: shivammathur/setup-php@v2
        with:
          extensions:
          ini-values: apc.enabled=1, apc.shm_size=32M, apc.enable_cli=1
          php-version: ${{ matrix.php }}

      - name: Install dependencies.
        if: matrix.php != '8.4'
        run: composer update $DEFAULT_COMPOSER_FLAGS

      - name: Install dependencies with PHP 8.4.
        if: matrix.php == '8.4'
        run: composer update $DEFAULT_COMPOSER_FLAGS --ignore-platform-reqs

      - name: Run tests with PHPUnit.
        run: vendor/bin/phpunit --verbose --colors=always
